baseurl = "https://sahilscss3blog.herokuapp.com/"
languageCode = "en-us"
title = "CSS3"
theme = "hyde-x"
author = "Meghana Raju"
# Shown in the side menu
copyright = "&copy; 2016. All rights reserved."
canonifyurls = true
paginate = 10

[indexes]
  tag = "tags"
  topic = "topics"
  [params]
    # Shown in the home page
    subtitle = "Making things beautiful"
    brand = "CSS3"
    googleAnalytics = "Your Google Analytics tracking ID"
    disqus = "Your Disqus shortname"
    # CSS name for highlight.js
    highlightjs = "androidstudio"
    dateFormat = "02 Jan 2006, 15:04"
    # Include any custom CSS and/or JS files
    # (relative to /static folder)
    customCSS = ""
    custom_js = ["js/my.js"]
    [menu]
      # Shown in the side menu.
      [[menu.main]]
        name = "Home"
        pre = "<i class='fa fa-home fa-fw'></i>"
        weight = 0
        identifier = "home"
        url = "/post/home"
        [[menu.main]]
    name = "Background"
    pre = "<i class='fa fa-user fa-fw'></i>"
    weight = 1
    identifier = "background"
    url = "/post/background"
  [[menu.main]]
    name = "Border"
    pre = "<i class='fa fa-user fa-fw'></i>"
    weight = 2
    identifier = "border"
    url = "/post/border"
  [[menu.main]]
    name = "Color"
    pre = "<i class='fa fa-user fa-fw'></i>"
    weight = 3
    url = "/post/color"
  [[menu.main]]
      name = "Multi-Column"
      pre = "<i class='fa fa-user fa-fw'></i>"
      weight = 4
      url = "/post/multi-column"
	      [[menu.main]]
      name = "Filters"
      pre = "<i class='fa fa-user fa-fw'></i>"
      weight = 5
      url = "/post/filters"
	  	      [[menu.main]]
      name = "Transitions"
      pre = "<i class='fa fa-user fa-fw'></i>"
      weight = 6
      url = "/post/transitions"
	  	      [[menu.main]]
      name = "Gradients"
      pre = "<i class='fa fa-user fa-fw'></i>"
      weight = 7
      url = "/post/gradients"
	  	  	      [[menu.main]]
      name = "Transforms"
      pre = "<i class='fa fa-user fa-fw'></i>"
      weight = 8
      url = "/post/transforms"

      [[menu.main]]
        name = "Animation"
        pre = "<i class='fa fa-user fa-fw'></i>"
        weight = 9
        url = "/post/animation"
      [[menu.main]]
      name = "Box-sizing"
      pre = "<i class='fa fa-user fa-fw'></i>"
      weight = 10
      url = "/post/box-sizing"
      [[menu.main]]
      name = "Flexible Box Layout"
      pre = "<i class='fa fa-user fa-fw'></i>"
      weight = 11
      url = "/post/flexibleBox"
