baseurl = "https://css3standards.herokuapp.com/post"
languageCode = "en-us"
title = "Hugo Learn Theme"
theme = "hugo-theme-learn"
MetaDataFormat = "yaml"

[params]
  author = "Sahil Pahuja | Meghana Raju"
