baseurl = "http://localhost:1313/"
languageCode = "en-us"
title = "Hugo Learn Theme"
theme = "hugo-theme-learn"
MetaDataFormat = "yaml"

[params]
  editURL = ""
  description = "Documentation for Hugo Learn Theme"
  author = "Mathieu Cornic"
