baseurl = "https://css3standards.herokuapp.com/post/topic"
languageCode = "en-us"
title = "CSS3 Standards"
theme = "hugo-theme-learn"
MetaDataFormat = "yaml"

[params]
  author = "Sahil Pahuja | Meghana Raju"
